import:
 - ~/.config/alacritty/catppuccin/catppuccin-mocha.yml

env:
  TERM: xterm-256color

font:
  normal:
    family: FiraCode Nerd Font
    style: Regular
  bold:
    family: FiraCode Nerd Font, Bold
    style: Bold
  italic:
    family: FiraCode Nerd Font, Light
    style: Italic
  bold_italic:
    family: FiraCode Nerd Font, Semibold
    style: Bold Italic
  size: 11

window:
  opacity: 0.9
  padding:
    x: 10
    y: 10

