tmux:
  symbols:
    branch: " "
    hashprefix: ":"
    ahead: "↑·"
    behind: "↓·"
    staged: "● "
    conflict: "✖ "
    modified: "✚ "
    untracked: "… "
    stashed: "⚑ "
    insertions: "Σ"
    deletions: "Δ"
    clean: "✔"

  styles:
    clear: "#[none]"
    state: "#[fg=#232634,bold]"
    branch: "#[fg=#232634,bold]"
    remote: "#[fg=#303446]"
    divergence: "#[fg=#303446]"
    staged: "#[fg=#232634,bold]"
    conflict: "#[fg=#232634,bold]"
    modified: "#[fg=#232634,bold]"
    untracked: "#[fg=#232634,bold]"
    stashed: "#[fg=#232634,bold]"
    insertions: "#[fg=#232634]"
    deletions: "#[fg=#232634]"
    clean: "#[fg=#232634,bold]"

  layout: [branch, " ", flags]

  options:
    branch_max_len: 40
    branch_trim: right
    ellipsis: "…"
    hide_clean: false
    swap_divergence: false
    divergence_space: false
    flags_without_count: false
