tmux:
  symbols:
    branch: " "
    hashprefix: ":"
    ahead: "↑·"
    behind: "↓·"
    staged: "● "
    conflict: "✖ "
    modified: "✚ "
    untracked: "… "
    stashed: "⚑ "
    insertions: "Σ"
    deletions: "Δ"
    clean: "✔"

  styles:
    clear: "#[fg=#c6d0f5,bg=#303446,nobold,noitalics,nounderscore]"
    state: "#[fg=#c6d0f5,bg=#303446,bold]"
    branch: "#[fg=#c6d0f5,bg=#303446,bold]"
    remote: "#[fg=#a5adce,bg=#303446]"
    divergence: "#[fg=#a5adce,bg=#303446]"
    staged: "#[fg=#8caaee,bg=#303446,bold]"
    conflict: "#[fg=#e78284,bg=#303446,bold]"
    modified: "#[fg=#f2d5cf,bg=#303446,bold]"
    untracked: "#[fg=#ca9ee6,bg=#303446,bold]"
    stashed: "#[fg=#81c8be,bg=#303446,bold]"
    insertions: "#[fg=#a6d189,bg=#303446]"
    deletions: "#[fg=#e78284,bg=#303446]"
    clean: "#[fg=#a6d189,bg=#303446,bold]"

  layout: [branch, " ", flags]

  options:
    branch_max_len: 40
    branch_trim: right
    ellipsis: "…"
    hide_clean: false
    swap_divergence: false
    divergence_space: false
    flags_without_count: false
