# Add any other personal Hyprland configuration below
# windowrule = workspace 5, match:class qemu
workspace = w[tv1], gapsout:40 200 40 200
workspace = r[1-4], monitor:$mainMonitor
workspace = 5, monitor:DP-3, default:true
# workspace = 5, monitor:DP-3, default:false
